[build]
  functions = "lambda"
  base = "."
  publish = "__sapper__/export"
  command = "npm run export"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
